apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: v1
appVersion: v1
dependencies:
  - name: cert-manager
    version: 1.11.1
    repository: https://charts.jetstack.io 